### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by jhnhp** [omerferhatt/torch2tflite#5]
I tried this code to convert my custom trained YOLOv5 model (.pt)
It returns this message

2021-05-31 10:26:03.181164: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
No module named 'models'

How can I fix this?

**Comment by Lola-Zhong** [comment]
I got the same problem and don't know how to fix this either

**Comment by mozeqiu** [comment]
> I got the same problem and don't know how to fix this either


I suggest to try the steps separately

**Comment by thongvhoang** [comment]
I got the same problem and don't know how to fix this either

**Comment by sayannath** [comment]
+1

> I got the same problem and don't know how to fix this either

**Comment by codebugged** [comment]
We are waiting @omerferhatt

**Comment by mozeqiu** [comment]
> 我们在等@omerferhatt

I have successfully converted, I will proceed in separate steps。like pt2onnx.py --> onnx2tf.py ---> tf2tflite.py,
Instead of finishing the conversion

**Comment by omerferhatt** [comment]
Hey everyone, sorry for late respond. I change code a little bit. Please test it out and lemme now if anything is broken.

**Comment by weinixuehao** [comment]
No module named 'model'
